name: sound_swap
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  get_it: ^8.0.3
  talker_flutter: ^4.4.1
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  vkid_flutter_sdk: ^1.0.0-alpha.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  